name: Build Manga Al-Arab APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Compile Manga Al-Arab APK
        run: |
          flutter create --org com.mangaalarab.app --project-name manga_alarab app_project
          cp -f lib/main.dart app_project/lib/main.dart
          cd app_project
          flutter build apk --release --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Manga-AlArab-Ultimate-APK
          path: app_project/build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
